exceptiongen/__init__.py,sha256=wJmwWJYusPMNRBVr7ooM1tezMjJ5fkxGJir4fa8xIj8,466
exceptiongenerator-2.3.dist-info/DESCRIPTION.rst,sha256=OCTuuN6LcWulhHS3d5rfjdsQtW22n7HENFRh6jC6ego,10
exceptiongenerator-2.3.dist-info/METADATA,sha256=ovA2q_cu2mCl-303sHUXnNE9nS7vwC3VGQFQbRB9ITg,281
exceptiongenerator-2.3.dist-info/RECORD,,
exceptiongenerator-2.3.dist-info/WHEEL,sha256=BTHHj6QhsHpWhRUrxioIvCAgjx81u-a8gkPTO6bi_A0,116
exceptiongenerator-2.3.dist-info/metadata.json,sha256=ivHnyyl8hQgkPGa9BsQk54_0DcNibwhMi4CkUHpvHzw,457
exceptiongenerator-2.3.dist-info/top_level.txt,sha256=vjzNUzV67RifbiU_t2Fbj2Si8c0By8uyEsC1SNZABBU,13
exceptiongenerator-2.3.dist-info/zip-safe,sha256=frcCV1k9oG9oKj3dpUqdJg1PxRT2RSN_XKdLCPjaYaY,2
