exceptiongen/__init__.py,sha256=4o6Tgsi-Qj349DkDKAmVYDibwsDLJfkZJsegHXHACyQ,357
exceptiongenerator-2.0.dist-info/DESCRIPTION.rst,sha256=OCTuuN6LcWulhHS3d5rfjdsQtW22n7HENFRh6jC6ego,10
exceptiongenerator-2.0.dist-info/METADATA,sha256=EaK1kH5UyATS5fj8K-x6_oED0I2Fj8ZAiOcsIuSHG-A,315
exceptiongenerator-2.0.dist-info/RECORD,,
exceptiongenerator-2.0.dist-info/WHEEL,sha256=BTHHj6QhsHpWhRUrxioIvCAgjx81u-a8gkPTO6bi_A0,116
exceptiongenerator-2.0.dist-info/metadata.json,sha256=-MVXxnOIh-Mes0HCH7VbUzgfPW2RrziWFt2CBjlBoyA,496
exceptiongenerator-2.0.dist-info/top_level.txt,sha256=vjzNUzV67RifbiU_t2Fbj2Si8c0By8uyEsC1SNZABBU,13
exceptiongenerator-2.0.dist-info/zip-safe,sha256=frcCV1k9oG9oKj3dpUqdJg1PxRT2RSN_XKdLCPjaYaY,2
